### ISSUE TITLE
Does not work with ember-cli-deploy-plugin 0.2.9

### ISSUE THREAD

**Issue by YoranBrondsema** [dschmidt/ember-cli-deploy-sentry#29]
Deploys fail with `TypeError: this.readConfig is not a function.`

See https://github.com/dschmidt/ember-cli-deploy-sentry/pull/28

**Comment by duizendnegen** [comment]
See #27 for a full fix
